### ISSUE TITLE
The Capture Selected Area Is Not working.

### ISSUE THREAD

**Issue by bekicot** [rojer/a-s-minus#1]
Hi,
Nice App, I like it.

However, the capture selected area is not working at all, I tested it on mac and ubuntu.

Let me know how to debug this, so i can give detailed report

Thanks,

Yana

**Comment by bekicot** [comment]
I have to open new tab, as it working on tab that is not opened during the installation.

Well, i will debug it and reopen the issue if i found proper repoduction if this issue.

**Comment by rojer** [comment]
hate to say it, but... works for me.
does it happen often? when it does, are there errors in the console? is the menu item enabled (i.e. not grayed out)?
do both keyboard shortcuts and menu item fail to trigger it?
are there any errors (from content_script.js, not the site itself) in the javascript console?

**Comment by bekicot** [comment]
There is no error in the console. 
It is working on most of the page, 
but doesnt work on these 
- http://www.smashingmagazine.com/search-results/?q=spinner&cx=partner-pub-6779860845561969%3A5884617103&cof=FORID%3A10&ie=UTF-8
- google sheets
- asana.com

**Comment by rojer** [comment]
ah, in that case yes, it is expected. functionality that is provided by
injected scripts (selective capture, full page capture and shortcuts) will
not work on tabs created before extension was installed.
it will also stop working on existing tabs when extension is updated.

**Comment by bekicot** [comment]
Sorry, you might get that from email. I actually made more test after a published that comments. And i found the error in these websites. So i updated the comments, as you might not notice the update from email.
- http://www.smashingmagazine.com/search-results/?q=spinner&cx=partner-pub-6779860845561969%3A5884617103&cof=FORID%3A10&ie=UTF-8
- google sheets
- asana.com

**Comment by bekicot** [comment]
Nevermind, weird error on my ubuntu lately. 

I'm sorry.
