### ISSUE TITLE
Capture entire page not working in chrome

### ISSUE THREAD

**Issue by ravigarg1** [rojer/a-s-minus#44]
Guys,

Please check the attached screenshot. Chrome version is "Version 61.0.3163.100 (Official Build) (64-bit)"

****
![image](https://user-images.githubusercontent.com/10277898/32268035-559bca4c-bf13-11e7-8bb4-9d494270a710.png)

**Comment by ralphcallaway** [comment]
seeing the same thing, let me know if there is any diagnostic info i can provide. happy to run a dev version with additional logging if that would help. seems like it's getting the bounding wrong somehow and thinks it's a 0x0 size page. thanks for providing an malware free version of this awesome extension, it's appreciated!!

here's the console log when i click capture entire page, no errors, the "scrollNext 0 0" log seems kid of strange
```
content_script.js:484 > init_entire_capture {action: "init_entire_capture"}action: "init_entire_capture"__proto__: Object
content_script.js:17 initEntireCapture
content_script.js:415 < scroll_next_done {action: "scroll_next_done"}action: "scroll_next_done"__proto__: Object
content_script.js:484 > scroll_next {action: "scroll_next"}action: "scroll_next"__proto__: Object
content_script.js:302 scrollNext 0 0
content_script.js:415 < entire_capture_done {action: "entire_capture_done", numColumns: 1, remainderRatio: {…}, scrollBar: {…}}action: "entire_capture_done"numColumns: 1remainderRatio: {y: 0, x: 0}scrollBar: {x: true, y: true}__proto__: Object
```

here's my system details 
![support_details___tech_support_management](https://user-images.githubusercontent.com/841021/32589938-d878b1fc-c4d4-11e7-8476-30c97c24b0cf.png)

here's what i get when i try to use the capture entire page
![annotate_your_screenshot](https://user-images.githubusercontent.com/841021/32589969-fff5832c-c4d4-11e7-8bd0-6d389351f973.png)

**Comment by abrightclearweb** [comment]
I get the same as @ravigarg1 & @ralphcallaway. Annoying as I really like the extension!

In my browser console, I see the message: "Cross-origin plugin content from  must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked."

If I try to capture a selected area, it still works as long as it's not taller than the height visible. If so, I only get the bottom half.

**Comment by imanzuk** [comment]
The same for me with Chrome 62.0.3202.94.

**Comment by jkayani** [comment]
One thing I noticed in bug triaging: capturing the entire page works fine for pages without any horizontal nor vertical scrollbars. For example, taking a screenshot of the entire page of https://www.google.com/ works.

It works because a page with no scrollbars fits entirely within what's visible in the browser, and so the extension treats the request as a screenshot for the visible portion of the page, which works fine (see content_script.js:32, `initEntireCapture`). 

Still looking into the main issue though; seems to be an issue with usage of `document.body.scrollTop` instead of `document.documentElement.scrollTop` and similar mixups. Because of this, it looks like the extension isn't scrolling and capturing the parts of the page as it should, so a 0x0 image is what appears on the canvas in the Edit view.

**Comment by jkayani** [comment]
Good news! I think I managed to figure it out, and fixed a few other issues with the entire page capture implementation along the way. 

In summary, my hypothesis was mostly right - the wrong browser API was being used to control the scrolling required to take an entire page screenshot. There was also a little weirdness with putting together several captures of a page with horizontal scroll into 1 cohesive image, but playing with the height/width calculations seems to have fixed that. If you're on a high-res screen, it'd be great for you test entire page capture and verify the solution works for you too.

**Comment by ralphcallaway** [comment]
@jkayani just gave your PR and it's working for me on simple long pages, working on my 4k monitor as well as an MBP retina display

noticed it has some issues on pages with multiple scrollbars, i.e. https://webpack.js.org/guides/getting-started/ although I'm guessing that's a separate issue, will log separately if that actually impacts me

fyi @rojer

**Comment by jkayani** [comment]
Here's what I observed on the page you linked:

When the extension scrolls down, an erroneous horizontal scrollbar appears, even though there wasn't one before. The portion of the page captured when using the erroneous scrollbar isn't useful, and seems like something weird with how the page is designed.

To fix this, we can check for scrollbars on a page once, at the start of capture (turn `scrollBar` into a global variable that's set for the page in `initEntireCapture`). Then during the capture, if erroneous scrollbars appear, we can record that they exist (`scrollBar.fakeX` and `scrollBar.fakeY`) and account for them later when laying out the captured tiles in the edit view. But we won't change `scrollBar.x` and `scrollBar.y`, so we do any unnecessary scrolling and capture useless parts of the page. I can add a commit to the PR to implement this if desired.

**Comment by satkunas** [comment]
Same issue on Chrome 63.0.3239.108 with Fedora 27 @ 4.14.3-300.fc27.x86_64

**Comment by jkayani** [comment]
Until the maintainer gets to merging this, you can use my fork which has the above PR already integrated in it: https://github.com/jkayani/a-s-minus/tree/fix-entire-capture

You'd just download the source code and load it as an unpacked extension, which you can find instructions for here: https://developer.chrome.com/extensions/getstarted#unpacked

**Comment by ccerrillo** [comment]
@rojer Why don't you merge this PR?

**Comment by rojer** [comment]
because i'm very busy with other things... sorry. looks ok, merging now.

also, i remember that i saw a change in chrome that provides native full page capture. we should use that instead, i think.
but for now, let's fix current code.

**Comment by ccerrillo** [comment]
@rojer Oh! I'm sorry for my interruption
@rojer @jkayani thanks for your well done work!

**Comment by ralphcallaway** [comment]
yay! thanks @rojer 

i really appreciate the contribution you've made maintaining this, i know this is something you've got to do in your free time and that's not easy :)

**Comment by rojer** [comment]
new version has been published

**Comment by ccerrillo** [comment]
@rojer Thanks!!
