### ISSUE TITLE
[Issue] Capture Desktop not working

### ISSUE THREAD

**Issue by HotPotSoup** [rojer/a-s-minus#6]
"Capture Desktop" does not work. It'd show my screen being recorded then nothing. If I stop sharing nothing pops up either.

**Comment by rojer** [comment]
what's the OS you're using? did you do anything that'd prevent chrome desktop notifications from working? after sharing the screen you should get a desktop notification which you click to do the capture.

fwiw i just tested the release version and it does work for me...

**Comment by HotPotSoup** [comment]
Windows 10 64 bit. Chrome Desktop Notifications are on and working (with other notification sources). I will try again after rebooting/disabling and re-enabling notifications though, and see if that'll fix the problem.
