### ISSUE TITLE
Shortcut bug

### ISSUE THREAD

**Issue by odie2** [rojer/a-s-minus#9]
Hi,

I just tried to write big "ś" (Ctrl+Alt+S) and I was surprised twice by taking screenshot of full page (in this case exactly 26732px height ^^).

I unchecked that shortcut on begin with extension and everything seems right on toolbar and on options page.
**Edit**, wait. It's taking full screen when it's shortcut for selected area. So this is even more strange ._.

Is this may be because Opera (installed extension with Download Chrome Extension) Developer v32.0 Windows? Or it's global bug?

![image](https://cloud.githubusercontent.com/assets/9401878/9370191/a177ed7a-46ce-11e5-8789-89ed81e811f0.png)

![image](https://cloud.githubusercontent.com/assets/9401878/9370196/b6db7ec0-46ce-11e5-8567-ee3da11d4264.png)

Greetings

**Comment by odie2** [comment]
Hey, any progress? Today tried wrote big "ś" again from 9 days.

**Comment by rojer** [comment]
sorry, absolutely no time to check this out, especially if it's in opera...
all i can say is that i cannot reproduce it in chrome - ctrl-alt-s doesn't trigger anything for me.
maybe it has something to do with diacritics, which i don't use... can you try it in chrome?

**Comment by odie2** [comment]
Ay, sorry I wrote wrong.

It's Shift + AltGr + S

However in Chrome 43.0.2357.81 the same.

My system locale is default Polish (Programmers). However checked with English and the same.

**Comment by rojer** [comment]
ha-ha, polish S strikes again :)
you know, i even read the article before abot this exact problem - https://medium.com/medium-eng/the-curious-case-of-disappearing-polish-s-fa398313d4df

i blame the original extension authors :)
ok, i'll fix it, this should be easy.

**Comment by odie2** [comment]
Thanks, will check it and get know.

Interesting article, I am in half of reading ;)

**Comment by odie2** [comment]
Thanks, will check it and let know.

Interesting article, I am in half of reading ;)

**Comment by rojer** [comment]
pushed to beta. i'll let it soak there for a day or two since it also picked up gdrive folder select featur, then push to stable.

**Comment by odie2** [comment]
Works nice. Thanks again ^^
ŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚŚ
